
import type { Artwork, Review } from './types';

export const artworks: Artwork[] = [
  {
    id: 1,
    title: 'Cosmic Bloom',
    artistStatement: 'A representation of the universe expanding from a single point of vibrant energy.',
    dimensions: '24" x 24"',
    medium: 'Acrylic on Canvas',
    price: 1200,
    availability: 'Available',
    type: 'Original',
    primaryColor: 'Blue',
    theme: 'Cosmic',
    imageUrl: 'https://picsum.photos/seed/cosmicbloom/600/600',
    images: ['https://picsum.photos/seed/cosmicbloom/1200/1200', 'https://picsum.photos/seed/cosmicdetail1/600/600', 'https://picsum.photos/seed/cosmicdetail2/600/600'],
  },
  {
    id: 2,
    title: 'Golden Sun',
    artistStatement: 'Capturing the warmth and life-giving energy of the sun in a symmetrical dance of light.',
    dimensions: '36" x 36"',
    medium: 'Mixed Media',
    price: 2500,
    discountedPrice: 2250,
    availability: 'Available',
    type: 'Original',
    primaryColor: 'Yellow',
    theme: 'Celestial',
    imageUrl: 'https://picsum.photos/seed/goldensun/600/600',
    images: ['https://picsum.photos/seed/goldensun/1200/1200', 'https://picsum.photos/seed/goldendetail1/600/600'],
  },
  {
    id: 3,
    title: 'Oceanic Depths',
    artistStatement: 'An exploration of the mysterious and serene world beneath the waves.',
    dimensions: '18" x 18"',
    medium: 'Acrylic on Wood Panel',
    price: 850,
    availability: 'Sold',
    type: 'Original',
    primaryColor: 'Cyan',
    theme: 'Nature',
    imageUrl: 'https://picsum.photos/seed/oceanicdepths/600/600',
    images: ['https://picsum.photos/seed/oceanicdepths/1200/1200'],
  },
  {
    id: 4,
    title: 'Crimson Fire',
    artistStatement: 'The passion and intensity of fire, contained within a balanced and intricate design.',
    dimensions: '12" x 12" Print',
    medium: 'Giclée Print',
    price: 150,
    availability: 'Available',
    type: 'Print',
    primaryColor: 'Red',
    theme: 'Elemental',
    imageUrl: 'https://picsum.photos/seed/crimsonfire/600/600',
    images: ['https://picsum.photos/seed/crimsonfire/1200/1200'],
  },
    {
    id: 5,
    title: 'Emerald Forest',
    artistStatement: 'A journey into the heart of an ancient forest, teeming with life and magic.',
    dimensions: '30" x 30"',
    medium: 'Acrylic on Canvas',
    price: 1800,
    availability: 'Available',
    type: 'Original',
    primaryColor: 'Green',
    theme: 'Nature',
    imageUrl: 'https://picsum.photos/seed/emeraldforest/600/600',
    images: ['https://picsum.photos/seed/emeraldforest/1200/1200', 'https://picsum.photos/seed/emeralddetail/600/600'],
  },
  {
    id: 6,
    title: 'Amethyst Dream',
    artistStatement: 'A meditative piece inspired by the calming and spiritual properties of amethyst crystals.',
    dimensions: '20" x 20"',
    medium: 'Mixed Media',
    price: 950,
    discountedPrice: 800,
    availability: 'Available',
    type: 'Original',
    primaryColor: 'Purple',
    theme: 'Spiritual',
    imageUrl: 'https://picsum.photos/seed/amethystdream/600/600',
    images: ['https://picsum.photos/seed/amethystdream/1200/1200'],
  },
  {
    id: 7,
    title: 'Monochrome Maze',
    artistStatement: 'Exploring the beauty of complexity through a simple black and white palette.',
    dimensions: '16" x 16" Print',
    medium: 'Giclée Print',
    price: 120,
    availability: 'Available',
    type: 'Print',
    primaryColor: 'White',
    theme: 'Abstract',
    imageUrl: 'https://picsum.photos/seed/monomaze/600/600',
    images: ['https://picsum.photos/seed/monomaze/1200/1200'],
  },
  {
    id: 8,
    title: 'Solar Flare',
    artistStatement: 'An explosive burst of creative energy, radiating outwards from a central point.',
    dimensions: '48" x 48"',
    medium: 'Acrylic on Canvas',
    price: 3500,
    availability: 'Reserved',
    type: 'Original',
    primaryColor: 'Orange',
    theme: 'Cosmic',
    imageUrl: 'https://picsum.photos/seed/solarflare/600/600',
    images: ['https://picsum.photos/seed/solarflare/1200/1200'],
  },
];

export const reviews: Review[] = [
  {
    id: 1,
    artworkId: 1,
    author: 'Jane D.',
    rating: 5,
    text: 'Absolutely stunning piece! The colors are even more vibrant in person. It has become the centerpiece of my living room.',
    date: '2023-10-15',
    status: 'approved',
  },
  {
    id: 2,
    artworkId: 1,
    author: 'Mark S.',
    rating: 4,
    text: 'Beautiful and intricate work. My only wish is that it was slightly larger. Still, very happy with the purchase.',
    date: '2023-11-01',
    status: 'approved',
  },
  {
    id: 3,
    artworkId: 2,
    author: 'Emily R.',
    rating: 5,
    text: 'The "Golden Sun" truly lights up the room. The detail is incredible. Worth every penny!',
    date: '2023-09-20',
    status: 'approved',
  },
  {
    id: 4,
    artworkId: 4,
    author: 'Chris T.',
    rating: 5,
    text: 'The print quality is fantastic. The colors are rich and the paper is high quality. Looks great framed.',
    date: '2023-12-05',
    status: 'approved',
  },
  {
    id: 5,
    artworkId: 1,
    author: 'Anonymous',
    rating: 3,
    text: 'It is okay.',
    date: '2023-12-10',
    status: 'pending',
  },
  {
    id: 6,
    artworkId: 5,
    author: 'Samantha B.',
    rating: 5,
    text: 'I feel like I can step right into this forest. It brings such a sense of peace to my study. I love it.',
    date: '2023-11-28',
    status: 'approved',
  },
];
